server:
  port: 8087

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

# Optional logging configuration for debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO