spring:
  application:
    name: audit-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: audit_db
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true